# Generated by Django 5.2 on 2025-05-18 11:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("movie_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="影片名称")),
                (
                    "genre",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="影片类型"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="影片时长（分钟）"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="导演"
                    ),
                ),
                (
                    "cast",
                    models.TextField(blank=True, default="", verbose_name="演员阵容"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="上映日期"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyAdmin",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="管理员账号",
                    ),
                ),
                ("user_name", models.CharField(max_length=32, verbose_name="管理员名")),
                (
                    "password",
                    models.CharField(max_length=64, verbose_name="管理员密码"),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "db_table": "管理员表",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "hall_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="影厅编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="影厅名称")),
                ("seat_count", models.PositiveIntegerField(verbose_name="座位总数")),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.movie",
                        verbose_name="正在播放的影片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="排片编号"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="票价",
                    ),
                ),
                (
                    "show_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="放映时间"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app01.hall",
                        verbose_name="影厅",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="app01.movie",
                        verbose_name="影片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户账号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        null=True,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, default=18, null=True, verbose_name="年龄"
                    ),
                ),
                (
                    "account",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "creat_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2025, 5, 18, 19, 52, 12, 119851),
                        null=True,
                        verbose_name="入职时间",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "男"), (2, "女")],
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_set",
                        to="app01.movie",
                        verbose_name="所属影片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "oid",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单号",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "待支付"), (2, "支付中"), (3, "已支付")],
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.myadmin",
                        verbose_name="管理员",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
