# Generated by Django 5.2 on 2025-05-18 11:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 5, 18, 19, 54, 56, 271623),
                null=True,
                verbose_name="入职时间",
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "seat_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="座位编号",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10, verbose_name="座位号")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "可用"), (1, "已预订"), (2, "已锁定")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="app01.hall",
                        verbose_name="影厅编号",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="app01.schedule",
                        verbose_name="排片编号",
                    ),
                ),
            ],
        ),
    ]
