# Generated by Django 5.2 on 2025-05-18 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_userinfo_creat_time_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="department",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=50, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 5, 18, 20, 29, 44, 306758),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
