# Generated by Django 5.2 on 2025-05-18 12:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_remove_userinfo_department_userinfo_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="admin",
        ),
        migrations.AddField(
            model_name="order",
            name="buy_time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="购买时间"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.schedule",
                verbose_name="排片编号",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.seat",
                verbose_name="座位编号",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.userinfo",
                verbose_name="用户编号",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 5, 18, 20, 42, 57, 149422),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
