# Generated by Django 5.2 on 2025-05-18 12:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_remove_order_admin_order_buy_time_order_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="buy_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="购买时间"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2025, 5, 18, 20, 44, 40, 979176),
                null=True,
                verbose_name="入职时间",
            ),
        ),
    ]
