# Generated by Django 5.2.1 on 2025-05-19 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_order_buy_time_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 19, 14, 46, 44, 416047), null=True, verbose_name='入职时间'),
        ),
    ]
