# Generated by Django 5.2.1 on 2025-05-19 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 19, 14, 56, 14, 693868), null=True, verbose_name='入职时间'),
        ),
    ]
